version: '3.8'

services:
  pgdb:
    container_name: pgdb_any
    image: postgres:15.4-alpine
    restart: always
    env_file:
      - ./anysite/.env
    environment:
      - ./anysite/.env
    volumes:
      - pgdb:/var/lib/postgresql/data
    ports:
      - "5438:5432"
#    networks:
#      - kafka_network

volumes:
  pgdb:

#networks:
#  kafka_network:
#    name: kafka_docker
#    external: true
